### ISSUE TITLE
Automatically startup when rebooting the VPS?

### ISSUE THREAD

**Issue by h1rule** [Kandru/ts3proxy#12]
Hey,

is there any way to automatic run ts3proxy whenever my VPS is rebooting?

**Comment by jake-fox** [comment]
gday, same thing.. is there a way to make this a ts3proxy.service, so it can restart on crash or system reboot?

**Comment by derkalle4** [comment]
Hi,

you can easily create such a file on your own with the help of systemd. The newer Ubuntu Server systems do use it. You can google tutorials for other linux systems. They do work quite similar.

See https://tecadmin.net/setup-autorun-python-script-using-systemd/ for full tutorial.

Assuming you have unpacked this GitHub repository in /opt/ with a folder name "ts3proxy" the following file should be suitable. You may save it as "ts3proxy.service". It is untested, so you maybe have to change "ExecStart" and "WorkingDirectory" to fit your needs.

[Unit]
Description=TS3proxy
After=multi-user.target
Conflicts=getty@tty1.service

[Service]
Type=simple
WorkingDirectory=/opt/ts3proxy/
ExecStart=/usr/bin/python3 python3 -m ts3proxy
StandardInput=tty-force

[Install]
WantedBy=multi-user.target

**Comment by jake-fox** [comment]
Hmm thanks for the reply, just inquiring what you mean by "new servers", im am having issues running the service on Ubuntu 16.04, would it be more worth while running on the latest versions of Ubuntu?

Working on getting this script working with  systemctl making it a runnable service, also happy to share working configs when i am successful. 

Example of my trauma
`root@AM-7S40848785749471X_2:~# sudo systemctl daemon-reload
root@AM-7S40848785749471X_2:~# sudo systemctl enable ts3proxy.service
root@AM-7S40848785749471X_2:~# sudo systemctl start ts3proxy.service
root@AM-7S40848785749471X_2:~# sudo systemctl status ts3proxy.service
● ts3proxy.service - TS3proxy
   Loaded: loaded (/lib/systemd/system/ts3proxy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-07-15 12:40:37 UTC; 3s ago
  Process: 2740 ExecStart=/usr/bin/python3 python3 -m ts3proxy (code=exited, status=2)
 Main PID: 2740 (code=exited, status=2)

Jul 15 12:40:37 AM-7S40848785749471X_2 systemd[1]: Started TS3proxy.
Jul 15 12:40:37 AM-7S40848785749471X_2 systemd[1]: ts3proxy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 15 12:40:37 AM-7S40848785749471X_2 systemd[1]: ts3proxy.service: Unit entered failed state.
Jul 15 12:40:37 AM-7S40848785749471X_2 systemd[1]: ts3proxy.service: Failed with result 'exit-code'.`

**Comment by jake-fox** [comment]
Just wanting to say for anyone else wanting to run this as a service with systemd1 on ubuntu 16.04, this is my method.

sudo nano  /lib/systemd/system/ts3proxy.service

#################################
[Unit]
Description=TS3proxy
After=multi-user.target
Conflicts=getty@tty1.service

[Service]
Type=simple
WorkingDirectory=/home/ts3proxy-master/ts3proxy
ExecStart= /usr/bin/python3 ts3proxy.py
StandardInput=tty-force
Restart=always

[Install]
WantedBy=multi-user.target
###############################

Thanks for the pointing me in the right direction.

**Comment by derkalle4** [comment]
Many thanks!
