### ISSUE TITLE
Banned all users

### ISSUE THREAD

**Issue by Pepe44DEV** [Kandru/ts3proxy#14]
If you ban people, everyone will be banned as the ip from the proxy

**Comment by derkalle4** [comment]
Hi @Pepe44DEV,

there is not much we can do about it (yet). Teamspeak Proxy is transparent to the Teamspeak server and the sense for it is to hide the origin of the Teamspeak 3 server. Therefore the user and the teamspeak server both have no idea where they are coming from. I will have a look in the future whether I can get the username vom the package data and provide it somewhere to the proxy so that one can ban a specific user IP via the banlist in the proxy.
