### ISSUE TITLE
Can be be ran from windows instead of linux?

### ISSUE THREAD

**Issue by wazerstar** [Kandru/ts3proxy#15]
as topic says 

If no, would you be willing to adapt it to also make it work for windows 10/11?

If yes could you provide guide on that too?

Further can this run with cloudflare?

**Comment by derkalle4** [comment]
Hi,

sorry for the late reply. But this repository is almost abandonedware. You can still use it (TS3 has nothing changed so far that I am aware of). Because this software does utilize Python it will run on Windows as well. I would not recommend to do so because Linux virtual machines are way more cheap and (depending on the configuration) are way more secure.

Please get familar on how to install Python on Windows properly. Afterwards download the source code, open a command line within the source code folder and and run the following commands:

pip3 install -e .
python3 -m ts3proxy

That should do the trick. If you get errors like "command not found" then please refer on the Python documentation on how to execute "python3" or "python" and "pip3" or "pip" on a windows system.

Kind Regards,
Kalle
