### ISSUE TITLE
[Question] What tools to use to log/get users ip

### ISSUE THREAD

**Issue by omnigenous** [Kandru/ts3proxy#18]
Not exactly this project related but it's something I need now I started using this.

I want to log few values of my teamspeak server users to log file:

1. IP
2. Connected/disconnected
3. Connected since timestamp

For example:

```
IP | Connected At | event
0.0.0.1    2024-08-31 12:25:00    connected
0.0.0.2    2024-08-31 15:15:00    connected
0.0.0.1    2024-08-31 15:26:00    disconnected after 3h 1m
```

---

And it would be nice to have real time dashboard as well with same values I listed above.
The best result I ever got is with `tcpdump -n -Q 'in' 'udp dst port 9987'` but then I had hundred different issues after trying to pipe it down to get unique IP only (it would wait like a minute before being process with `awk` or I would need use `stdbuf` when piping to `cut` or similar tools).

**Comment by derkalle4** [comment]
Hi @omnigenous ,

this could easily be implemented with little knowledge of Python at all (e.g. with ChatGPT). This repository is not actively maintained and I do not see any benefit from implementing this for one user. Keep in mind: Only IP + Port combinations are possible to log. We transparently sync the data via our proxy to the teamspeak server itself without intercepting the protocol. So we do not know the usernames nor other data of the user.

For your log format: I would suggest to add multiple rows for easier parsing:
IP | Port | event | seconds_connected | timestamp

Though the seconds_connected could be omitted because you could easily generate this from the timestamp data.
