### ISSUE TITLE
Use ServerQuery for weblist

### ISSUE THREAD

**Issue by Bluscream** [Kandru/ts3proxy#3]
That would provide a easy way to get the required information on a regular basis and you can warn the user if the original IP is still present on the weblist + maybe offer to change it for him.
Also this would not require any user interaction when the servername/slots/etc. change.

The PIP package `ts3` might be a good library to use :3

**Comment by derkalle4** [comment]
Don't really want that in the ts3proxy because it's meant to be an standalone solution. A server owner should be able to configure max users to the same limit like the ts3 server has. So the information wouldn't be different. And as I said in the forums an admin user should be able to make a simple click in the teamspeak server settings of course.

**Comment by Bluscream** [comment]
> So the information wouldn't be different

The information would indeed be different as the online clients only count proxy connections what not everybody wants
