### ISSUE TITLE
Pass through client ips ?

### ISSUE THREAD

**Issue by Synkstar** [Kandru/ts3proxy#9]
I am wondering if it is possible to make it pass through the clients ip addresses.

**Comment by derkalle4** [comment]
Can you please specify what you mean? I think I do not understand...

**Comment by Synkstar** [comment]
Well when a client connects to the teamspeak through the proxy it shows the proxy server ip and not the clients origin ip. I was wondering if it was even possible to have it show the origin ip.

**Comment by derkalle4** [comment]
Unfortunately this is not technically possible. It is possible to sent UPD packages with another IP address (used for UDP flooding and therefore UDP DoS and DDoS attacks). And because Teamspeak is closed source I don't have any possibility to manipulate the data stream itself.

But if you wan't to see the origin IP address then simply don't use the proxy ;) it's meant to hide the servers IP and client IP. To be able to kick specific users you would need something that lists all connected IP addresses. But then you will have to match the IP addresses to users somehow. I don't have a way to get any data from inside the ts3 protocol for now because it's closed source.

**Comment by Bluscream** [comment]
Client IPs are essential for some TeamSpeak related tools (most teamspeak webscripts use the ip to link users between a website and the TS client) and most importantly banning. Clients using the proxy are essentially immune to banning because new IDs are so cheap to make, especially for bad guys. Also you can't really ban at all when using the proxy because the internal `banclient` command always includes the client's ip (in that case the proxy ip) and you would ban everyone connecting via it. You would either have a custom ban plugin like [this one](https://github.com/Bluscream/pytson_plugins/tree/master/scripts/customBan) or add only the uid to the banlist manually (both of which are impossible on mobile devices). 

I mean it's not HTTP but don't UDP packets have headers too? If yes, why not send smth like `TS_FORWARDED_FOR: XX.XX.XX.XX` to the real server and i'll see what i can do from there :)

> It is possible to sent UPD packages with another IP address

Why not use that?

**Comment by derkalle4** [comment]
I know how Teamspeak works and what get's easier with that or not. But it is currently not possible for me to do this kind of stuff because I cannot hijack the UDP session of Teamspeak. And the TS3 protocol is encrypted so I cannot even change something inside the packets because I simply do not know what exactly is inside nor I am able to encrypt it again to give Teamspeak an understanding what I want to do.

Sure, UDP packets got headers. But you cannot compare HTTP headers with UDP headers. HTTP is based on TCP, so the "headers" you mean are actually in the protocol HTTP and not TCP. You should simply look at wikipedia for all the differences.

When I change the source IP address from within the proxy, the TS3 will think that it talks directly to the client, for sure. But the answer of the traffic then will not be sent back to the proxy - it will directly sent to the client because the Teamspeak 3 server only know his IP. This is called UDP spoofing and widely used for UDP flooding (DoS and DDoS) on for example game server query protocols. This will not be helpful for communicating with the Teamspeak 3 Server. If you want to figure out just try it with this library: https://stackoverflow.com/questions/38956401/ip-spoofing-in-python-3

And sth like "TS_FORWARDED_FOR" could be a valid header for HTTP, not for TCP nor UDP.
See:
https://en.wikipedia.org/wiki/List_of_HTTP_header_fields
https://en.wikipedia.org/wiki/User_Datagram_Protocol#Packet_structure
https://en.wikipedia.org/wiki/Transmission_Control_Protocol#TCP_segment_structure

**Comment by Synkstar** [comment]
You would probs need to get teamspeak in on it. It would be cool if they can make an anti ddos service or give you access to the tools you need like this but made by teamspeak and better integrated

**Comment by Synkstar** [comment]
Teamspeak kinda need to up there game especially the licencing. They should make it so that businesses have to pay and non businesses can do what ever they want. Or atleast make it cheaper for a licence. Maybe an open source version

**Comment by Bluscream** [comment]
Is it possible to add any payload at all to one of teamspeaks UDP packet without destroying it? If so TeaSpeak could make use of that payload.

**Comment by Synkstar** [comment]
Do you guys know what QUIC is well its an experimental protocol that googles youtube uses. QUIC is basically like tcp over udp https://en.wikipedia.org/wiki/QUIC

**Comment by Bluscream** [comment]
Teamspeak uses plain udp, if you would convert a teamspeak udp package to a QUIC package the server couldn't read it anymore

**Comment by derkalle4** [comment]
This issue is closed. Please get yourself familiar with protocols and stuff before reopening any issue. Thanks!
